FROM ros:noetic-ros-core

RUN apt-get update \
    && apt-get install -y build-essential file clang-format python3-rosdep \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# workaround for https://github.com/catkin/catkin_tools/issues/594:
# apt-get install python3-catkin-tools doesn't work because running catkin throws the following error:
# pkg_resources.DistributionNotFound: The 'osrf-pycommon>0.1.1' distribution was not found and is required by catkin-tools

RUN apt-get update \
    && apt-get install -y python3-osrf-pycommon python3-catkin-tools \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# end workaround

# Create ROS workspace
COPY . /ws/src/phidgets_drivers
WORKDIR /ws

# Use rosdep to install all dependencies (including ROS itself)
RUN rosdep init && rosdep update && rosdep install --from-paths src -i -y --rosdistro noetic

RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && \
    python3 src/phidgets_drivers/clang-check-style.py && \
    catkin init && \
    catkin config --install -j 1 -p 1 && \
    catkin build --limit-status-rate 0.1 --no-notify && \
    catkin build --limit-status-rate 0.1 --no-notify --make-args tests"
